<a href="https://colab.research.google.com/github/KondoKoyo/EU_M_Math/blob/main/Chap05_Cm_01~09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mp1
%matplotlib inline
%precision 3


'%.3f'

In [5]:
sample_array = np.arange(10)
print('sample_array:',sample_array)

sample_array: [0 1 2 3 4 5 6 7 8 9]


In [6]:
print(sample_array)
sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [7]:
sample_array_slice[0:3] = 10
print(sample_array_slice)
print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [8]:
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)
print(sample_array)


[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [9]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)


['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [ ]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [10]:
data[sample_names == 'a']


array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [ ]:
cond_data = np.array([True,True,False,False,True])

x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])
print(np.where(cond_data,x_array,y_array))

[  1   2 300 400   5]


In [11]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)
# print(sample_names)
# print(data)
print(data[sample_names=='b']) #練習問題5-1
sample_names = np.array(['a','a','c','a','a'])#練習問題5-2
print(data[sample_names=='a'] )

x_array = np.array([1,2,3,4,5])
y_array = np.array([6,7,8,9,10])
cond_data = np.array([False,False,True,True,False])
print(np.where(cond_data,x_array,y_array))     #練習問題5-3


[[-0.977  0.95  -0.151 -0.103  0.411]]
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]
[ 6  7  3  4 10]


In [12]:
cond_data = np.array([True,True,False,False,True])
print(cond_data)

print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [13]:
sample_data = np.arange(10)
print('元のデータ：',sample_data)
print('すべての要素の平方根：',np.sqrt(sample_data))
print('すべての要素のネイビア指数関数:',np.exp(sample_data))


元のデータ： [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根： [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイビア指数関数: [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [14]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print('最小値:',sample_multi_array_datal.min())
print('最大値:',sample_multi_array_datal.max())
print('平均:',sample_multi_array_datal.mean())
print('合計:',sample_multi_array_datal.sum())

print('行の合計:',sample_multi_array_datal.sum(axis =1))
print('列の合計:',sample_multi_array_datal.sum(axis = 0))


最小値: 0
最大値: 8
平均: 4.0
合計: 36
行の合計: [ 3 12 21]
列の合計: [ 9 12 15]


In [15]:
conda_data = np.array([True,True,False,False,True])
print('Trueが少なくとも１つあるかどうか：',conda_data.any())
print('すべてTrueかどうか：',cond_data.all())



Trueが少なくとも１つあるかどうか： True
すべてTrueかどうか： False


In [16]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)
print('５より大きい数字がいくつあるか：',(sample_multi_array_datal>5).sum())


[[0 1 2]
 [3 4 5]
 [6 7 8]]
５より大きい数字がいくつあるか： 3


In [17]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)
print('対角成分：',np.diag(sample_multi_array_datal))
print('対角成分の和',np.trace(sample_multi_array_datal))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分： [0 4 8]
対角成分の和 12


In [18]:
sample_multi_array_datal2 = np.arange(16).reshape(4,4)
sample_multi_array_datal2
print('平方根：',np.sqrt(sample_multi_array_datal2))   #練習問題5-4
print('最小値:',sample_multi_array_datal2.min())     #練習問題5-5
print('最大値:',sample_multi_array_datal2.max())
print('平均:',sample_multi_array_datal2.mean())
print('合計:',sample_multi_array_datal2.sum())

print('対角成分の和',np.trace(sample_multi_array_datal2))  #練習問題5-6



平方根： [[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]
最小値: 0
最大値: 15
平均: 7.5
合計: 120
対角成分の和 30


In [19]:
sample_array1 = np.arange(12).reshape(3,4)  #練習問題5-7
sample_array2 = np.arange(12).reshape(3,4)

print(np.concatenate([sample_array1,sample_array2],axis=0))  #練習問題5-8
print(np.concatenate([sample_array1,sample_array2],axis=1))





[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [20]:
sample_list = np.array([1,2,3,4,5])    #練習問題5-9
sample_list+3


array([4, 5, 6, 7, 8])